version: '2.1'
services:
    dockbeat:
        container_name: dockbeat-server
        build: ../services/dockbeat
        image: ../services/dockbeat
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        env_file:
            - ../services/env
        networks:
            - elastest
    elastest-platform-manager:
        container_name: elastest-epm
        image: elastest/epm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        expose:
            - 8180
        ports:
            - 8180:8180
        networks:
            - elastest
        links:
            - dockbeat
networks:
    elastest:
        driver: bridge