version: '2.1'
services:
    epm:
        container_name: elastest-epm
        image: elastest/epm
        entrypoint: java -jar elastest-platform-manager-0.1.0.jar
        environment:
            - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
            - ET_EDM_MYSQL_HOST=edm-mysql
            - ET_EDM_MYSQL_PORT=3306
            - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
            - ET_EDM_API=http://edm:37001/
            - ET_EPM_API=http://epm:37001/
            - ET_ETM_API=http://etm:37001/
            - ET_ESM_API=http://esm:37001/
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        expose:
            - 8180
        ports:
            - 37002:8180
        networks:
            - elastest
networks:
    elastest:
        driver: bridge
